# Generated by Django 4.1.7 on 2023-06-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartxapp', '0002_alter_userprofile_age_alter_userprofile_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='request',
        ),
        migrations.AddField(
            model_name='order',
            name='request',
            field=models.ManyToManyField(blank=True, related_name='requested_orders', to='apartxapp.worker'),
        ),
    ]
