# Generated by Django 4.1.7 on 2023-06-24 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartxapp', '0003_remove_order_request_order_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='request',
            new_name='requested_by',
        ),
    ]
