# Generated by Django 4.1.7 on 2023-06-24 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apartxapp', '0004_rename_request_order_requested_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='doc_picture',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='experience',
        ),
        migrations.AddField(
            model_name='order',
            name='videofraud',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='doc_picture',
            field=models.ImageField(default='noavatar.jpg', upload_to='doc_pictures'),
        ),
        migrations.AddField(
            model_name='worker',
            name='city',
            field=models.CharField(default='Astana', max_length=255),
        ),
        migrations.AddField(
            model_name='worker',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='profession',
            field=models.CharField(default='Cleaner', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.CreateModel(
            name='FreeTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='worker',
            name='free_times',
            field=models.ManyToManyField(blank=True, to='apartxapp.freetime'),
        ),
    ]
