# Generated by Django 4.1.7 on 2023-06-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartxapp', '0005_remove_customer_doc_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='doc_picture',
            field=models.ImageField(blank=True, default='noavatar.jpg', upload_to='doc_pictures'),
        ),
    ]
