# Generated by Django 4.1.7 on 2023-06-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartxapp', '0008_order_rating_worker_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='videofraud',
        ),
        migrations.AddField(
            model_name='order',
            name='photofraud1',
            field=models.ImageField(blank=True, upload_to='photo_frauds'),
        ),
        migrations.AddField(
            model_name='order',
            name='photofraud2',
            field=models.ImageField(blank=True, upload_to='photo_frauds'),
        ),
        migrations.AddField(
            model_name='order',
            name='photofraud3',
            field=models.ImageField(blank=True, upload_to='photo_frauds'),
        ),
        migrations.AddField(
            model_name='order',
            name='photofraud4',
            field=models.ImageField(blank=True, upload_to='photo_frauds'),
        ),
    ]
